model: 'resnet18'
pretrained: 'imagenet'
weights: 'models/best_model.pt'
device: 'cuda'

path-to-dataset: 'UTKFace_Dataset/'
save-models-path: 'models/'
save-results-path: 'output/'
source-path: 'misc/'
img-size: 224


learning-rate: 0.001
momentum: 0.9

batch-size: 64
epochs: 20
patience: 5

